version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev